// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":return img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`;
            case "image3":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
            case "image5":return img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image7":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image6":return img`
. . . . . f f f f . . . . . . . 
. . . f f e e e e f f . . . . . 
. . f e e e f f e e e f . . . . 
. f f f f f 2 2 f f f f f . . . 
. f f e 2 e 2 2 e 2 e f f . . . 
. f e 2 f 2 f f 2 f 2 e f . . . 
. f f f 2 2 e e 2 2 f f f . . . 
f f e f 2 f e e f 2 f e f f . . 
f e e f f e e e e f e e e f . . 
. f e e e e e e e e e e f . . . 
. . f e e e e e e e e f . . . . 
. e 4 f f f f f f f f 4 e . . . 
. 4 d f 2 2 2 2 2 2 f d 4 . . . 
. 4 4 f 4 4 4 4 4 4 f 4 4 . . . 
. . . . f f f f f f . . . . . . 
. . . . f f . . f f . . . . . . 
`;
            case "image8":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
            case "image9":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. b b b f 2 2 2 2 2 2 f b b b . 
b 2 7 2 b 2 2 2 2 2 2 b 7 2 7 b 
b 7 2 7 b 4 4 5 5 4 4 b 2 7 2 b 
b 2 7 2 b f f f f f f b 7 2 7 b 
. b b b . f f . . f f . b b b . 
`;
            case "image10":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image1":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image11":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
